version: "3.3"
services:

#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile.dev
#    ports:
#        - 3000:3000
#    container_name: mern-frontend
#    networks:
#      -  mern-stack-net
#    volumes:
#      -  ./frontend/src:/usr/app/src
#      -  ./frontend/public:/usr/app/public
#    depends_on:
#      - backend
#    stdin_open: true
#    tty: true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
    container_name: mern-frontend
    networks:
      - mern-stack-net
    volumes:
      - ./frontend/src:/usr/app/src
      - ./frontend/public:/usr/app/public
    depends_on:
      - backend
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - 3001:3001
    container_name: mern-backend
    networks:
      - mern-stack-net
    volumes:
      - ./backend/src:/usr/app/src

networks:
  mern-stack-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local